<script>
	/* THIS FILE IS AUTOGENERATED */
	import { onMount } from 'svelte'
	import { TYPES } from '$mxz/Defs.js'
	import { _UNIFORMS, _HIDDEN } from '$mxz/Store.js'
	import { SetOpCallback } from '$mxz/API.js'
	import Auto from '$mxz/gui/Auto.svelte'
	import schema from '$mxz/ops/Convolution.json'
	import shader from '$mxz/ops/Convolution.glsl'
	import Uniforms from '$mxz/Uniforms.svelte'
	export let name
	export let uuid
	export let colIdx
	export let rowIdx

	const SAY = (m, e) => console.log(`[Convolution] ${m}`, e || '')

	let TMO
	$: (UNIS => (SetOpCallback({name,uuid,schema})))($_UNIFORMS)

</script>
<Uniforms {name} {uuid} {schema} {shader} {colIdx} {rowIdx} />